name: Update Blocklist

on:  # Define the events that trigger the workflow
  schedule:
    - cron:  '0 * * * *' # Check Every Hours
  workflow_dispatch:
  
jobs:
  update-blocklist:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT_GITHUB_TOKEN || github.token }}

      - name: Setup WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard resolvconf
          echo "${{ secrets.WIREGUARD_CONFIG }}" > wg0.conf
          sudo mv wg0.conf /etc/wireguard/wg0.conf
          sudo wg-quick up wg0
        shell: bash
        continue-on-error: false

      - name: Run update script
        run: |
          chmod +x update.sh  # Make update.sh executable
          ./update.sh  # Run the script
        shell: bash
        continue-on-error: false

      - name: KillGuard
        run: |
          sudo wg-quick down wg0
        shell: bash
        continue-on-error: false

        env:  # Set environment variables for sensitive data
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          DOMAIN_URL: ${{ secrets.SOURCE_URL }}
          IP_URL: ${{ secrets.SOURCE_URL2 }}
          SITUS_JUDI: ${{ secrets.SITUS_JUDI }}
