name: Update Blocklist

on:
  schedule:
    - cron: '0 * * * *' # Check Every Hour
  workflow_dispatch:

jobs:
  update-blocklist:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT_GITHUB_TOKEN || github.token }}

      # Step 2: Print Environment Variables (Debugging)
      - name: Print environment variables
        run: |
          echo "DOMAIN_URL=${{ secrets.SOURCE_URL }}"
          echo "IP_URL=${{ secrets.SOURCE_URL2 }}"
          echo "SITUS_JUDI=${{ secrets.SITUS_JUDI }}"

      # Step 3: Download the files and verify
      - name: Download files
        run: |
          echo "Downloading files from the provided URLs..."
          curl --insecure -m 300 -o "domains.txt" "$DOMAIN_URL"
          curl --insecure -m 300 -o "ipaddress_isp.txt" "$IP_URL"
          curl --insecure -m 300 -o "situs_judi.txt" "$SITUS_JUDI"

          # Check if files are downloaded successfully
          if [[ ! -f "domains.txt" || ! -f "ipaddress_isp.txt" || ! -f "situs_judi.txt" ]]; then
            echo "Error: One or more files failed to download. Exiting."
            exit 1
          else
            echo "Files downloaded successfully."
          fi
        env:
          DOMAIN_URL: ${{ secrets.SOURCE_URL }}
          IP_URL: ${{ secrets.SOURCE_URL2 }}
          SITUS_JUDI: ${{ secrets.SITUS_JUDI }}

      # Step 4: Install GitHub CLI (for uploading release assets)
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      # Step 5: Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Step 6: Create or Update GitHub Release and Upload Files
      - name: Create or Update Release and Upload Files
        run: |
          # Use only timestamp as the tag (e.g., YYYYMMDDHHMM)
          TIMESTAMP=$(date +'%Y%m%d%H%M')
          TAG="${TIMESTAMP}"

          echo "Creating or updating release with tag: $TAG"

          # Create a new release
          gh release create "$TAG" \
            --title "Update Blocklist - $TIMESTAMP" \
            --notes "Automated update containing the latest blocklist files."

          # Upload files to the new release
          gh release upload "$TAG" domains.txt --clobber
          gh release upload "$TAG" ipaddress_isp.txt --clobber
          gh release upload "$TAG" situs_judi.txt --clobber

      # Step 7: Clean up environment
      - name: Cleanup
        run: |
          rm -f domains.txt ipaddress_isp.txt situs_judi.txt
